Allow to edit either home or readme If both are edited then it will cause an error and stop the workflow

diff --git a/.github/workflows/sync-wiki.yml b/.github/workflows/sync-wiki.yml
--- a/.github/workflows/sync-wiki.yml
+++ b/.github/workflows/sync-wiki.yml
@@ -27,6 +27,13 @@ jobs:
           filters: |
             src:
               - 'wiki/**'
+      - name: Set wiki/Home.md path
+        uses: dorny/paths-filter@v2
+        id: home
+        with:
+          filters: |
+            src:
+              - 'wiki/Home.md'
       - name: Set README.md path
         uses: dorny/paths-filter@v2
         id: readme
@@ -34,6 +41,13 @@ jobs:
           filters: |
             src:
               - 'README.md'
+      - name: Prevent Conflicts
+        if: |
+          steps.readme.outputs.src == 'true' &&
+          steps.readme.outputs.src == 'true'
+        run: |
+            echo "Error: Conflicting changes. Edit either the README.md file or the wiki/Home.md file, not both."
+            exit 1
       - name: Set github bot global config
         run: |
           git config --global user.email "actions@github.com"
@@ -44,6 +58,13 @@ jobs:
           cp -r $GITHUB_WORKSPACE/README.md $GITHUB_WORKSPACE/wiki/Home.md
           git add wiki/Home.md
           git commit -m "Auto update wiki/Home.md"
+          git push
+      - name: Sync wiki/Home.md to README.md
+        if: steps.home.outputs.src == 'true'
+        run: |
+          cp -r $GITHUB_WORKSPACE/wiki/Home.md $GITHUB_WORKSPACE/README.md
+          git add README.md
+          git commit -m "Auto update README.md"
           git push
       - name: Sync all files to wiki
         if: steps.wiki.outputs.src == 'true'
